name: Production testing & deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install package
        run: cd vite && yarn
      - name: Build
        run: cd vite && yarn run build
      - uses: actions/upload-artifact@v1
        with:
          name: build_file
          path: vite/dist
