name: Production testing & deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install lib package
        run: cd firestore-serializers && yarn
      - name: Build lib package
        run: cd firestore-serializers && yarn build
      - name: Install lib tree
        run: cd tree && yarn
      - name: Build lib tree
        run: cd tree && yarn build
      - name: Install Vite package
        run: cd vite && yarn
      - name: Build Vite
        run: cd vite && yarn run build
      - name: Install electron package
        run: cd server && yarn
      - name: Build Electron
        run: cd server && yarn run package
      - uses: actions/upload-artifact@v1
        with:
          name: build_file
          path: vite/dist
      - uses: actions/upload-artifact@v1
        with:
          name: electron_file
          path: server/out
